# Generated by Django 5.1.4 on 2025-01-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='33, 10, 230', max_length=13),
        ),
    ]
