# Generated by Django 5.1.4 on 2025-01-14 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tag_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_picture',
            new_name='profile_image',
        ),
    ]
